<a href="https://colab.research.google.com/github/manojvp16/Ai-Engineer/blob/main/numpytutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr =np.array([1,2,3,4,5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
a=np.array([[],[]])
a.ndim
a.shape

(2, 0)

In [ ]:
arr2=np.arange(1,11,2) # start. stop, step

In [ ]:
arr2

array([1, 3, 5, 7, 9])

In [ ]:
arr=np.linspace(0,1,5)

In [ ]:
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr=np.logspace(1,3,3)#10^1-10^3 , 3 numbers

In [ ]:
arr

array([  10.,  100., 1000.])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr=np.full(10,2)#number of values and which value

In [ ]:
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr=np.full([2,4],7) # rows columns and default values
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
arr=np.empty([2,3])

In [ ]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr=np.random.rand(2,3)

In [ ]:
arr

array([[0.2055766 , 0.98088699, 0.77482555],
       [0.53303814, 0.24752054, 0.61441457]])

In [ ]:
arr=np.random.rand(10)
arr

array([0.7249212 , 0.43509673, 0.71363543, 0.27028849, 0.65140353,
       0.06604511, 0.7823307 , 0.77013444, 0.5117739 , 0.14492834])

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr=np.array([1,2,3,4,5],dtype=np.float64)

In [ ]:
arr

array([1., 2., 3., 4., 5.])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
#type casting is done uing astype() method

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
newarr=arr.astype(np.float64)
newarr

array([1., 2., 3., 4., 5.])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.itemsize

8

In [ ]:
#reshape


In [ ]:
arr=np.array([1,2,3,4,5,6])

In [ ]:
reshaped = arr.reshape(3,2)
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
reshapess=arr.reshape(2,3)
reshapess

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
oned=reshapess.ravel()

In [ ]:
oned

array([1, 2, 3, 4, 5, 6])

In [ ]:
flat = reshapess.flatten()

In [ ]:
flat

array([1, 2, 3, 4, 5, 6])

In [ ]:
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
oned

array([1, 2, 3, 4, 5, 6])

Arethimatic Operation

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [ ]:
print(a+b)

[ 7  9 11 13 15]


In [ ]:
print(b-a)

[5 5 5 5 5]


In [ ]:
print(a*b)

[ 6 14 24 36 50]


In [ ]:
print(a/b) # for float

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
print(a//b)

[0 0 0 0 0]


In [ ]:
print(b//a) # for int

[6 3 2 2 2]


In [ ]:
print(a%b) # modulo

[1 2 3 4 5]


In [ ]:
print(a**2) #power

[ 1  4  9 16 25]


## **Universal Function**

In [ ]:
arr = np.array([1,4,9,16])

In [ ]:
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [ ]:
#exponential -?np.exp() ->e^x = where x is and integer

In [ ]:
print(np.exp([1,2])) # e^1 =2.7 & e^2 =7.4

[2.71828183 7.3890561 ]


In [ ]:
#sine-sine(0)

In [ ]:
angles=np.array([0,30,45,60,90])
print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]
